/// Flutter icons CustomCar
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomCar
///      fonts:
///       - asset: fonts/CustomCar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomCar {
  CustomCar._();

  static const _kFontFam = 'CustomCar';
  static const String? _kFontPkg = null;

  static const IconData car = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
